#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef HAL_PROXIMITY_ENABLED
#define HAL_PROXIMITY_ENABLED (!HAL_MINIMIZE_FEATURES && BOARD_FLASH_SIZE > 1024)
#endif

#ifndef AP_PROXIMITY_LDROBOT_STL27L_ENABLED
#define AP_PROXIMITY_LDROBOT_STL27L_ENABLED AP_PROXIMITY_BACKEND_DEFAULT_ENABLED
#endif